generate-github-directory:
  version: 0.1.1
  tag: latest
  module: commonjs
  packageJson:
    bin:
      'generate-github-directory': ./bin/generate-github-directory.js
      'ghdir': ./bin/generate-github-directory.js
    keywords:
      - generate
      - github