copy-github-directory:
  version: 1.3.0-alpha.1
  tag: canary
  module: commonjs
  packageJson:
    bin:
      'copy-github-directory': ./bin/copy-github-directory.js
      'ghcopy': ./bin/copy-github-directory.js
    keywords:
      - github
      - clone
      - download