copy-github-directory:
  version: 1.3.1
  tag: latest
  packageJson:
    bin:
      'copy-github-directory': ./bin/copy-github-directory.js
      'ghcopy': ./bin/copy-github-directory.js
    keywords:
      - github
      - clone
      - download